#!/bin/bash


echo Digite a url
read url

google-chrome --new-tab "https://www.google.com/search?q=-site:$url link:$url" # Search for other sites that are linking to our target
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:admin | administrator | adm | login | l0gin | wp-login" # Login panel search
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"login" "admin"" # Login panel search #2
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:admin" # Admin panel search
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:txt | ext:doc | ext:docx | ext:odt | ext:pdf | ext:rtf | ext:sxw | ext:psw | ext:ppt | ext:pptx | ext:pps | ext:csv | ext:mdb" # Search for our target's exposed files
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /" Parent Directory" # Get open directories (index of)
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /admin"" # Search for exposed admin directories
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /password"" # Search for exposed password directories
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /mail"" # Search for directories with mail
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /" (passwd | password.txt)" # Search for directories containing passwords
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of /" .htaccess" # Search for directories containing .htaccess
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:passwd filetype:txt" # Search for .txt files with passwords
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:admin filetype:db" # Search for potentially sensitive database files
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:log" # Search for log files
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:login" #This Google dork will search for login pages on a specific website. Hackers can use this to find unsecured login pages and gain access to sensitive information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:pdf intext:password" #This Google dork will search for PDF files containing passwords. This is a common way for hackers to find login credentials.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:ini" #This Google dork will search for various configuration files on a specific website, which may contain sensitive information such as login credentials or database connection strings.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”powered by wordpress”" #This Google dork will search for websites that are powered by WordPress, which may have vulnerabilities that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “config.php”" #This Google dork will search for config.php files on a website, which may contain sensitive information such as database credentials.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/admin/login.php" #This Google dork will search for login pages for a website’s admin panel, which may have vulnerabilities that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”phpinfo()”" #This Google dork will search for phpinfo() pages on a website, which can reveal information about a website’s PHP configuration that can be useful for hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:log" #This Google dork will search for log files on a website, which can contain sensitive information such as IP addresses, login attempts, and errors.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”login” inurl:”/admin”" #This Google dork will search for admin login pages on a website, which can be used by hackers to gain access to an admin panel.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”Error Message : Error loading required libraries.”" #This Google dork will search for websites that have missing or outdated libraries, which can indicate a vulnerability that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:sql password" #This Google dork will search for SQL databases that contain passwords, which can be used by hackers to gain unauthorized access to a website.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/password.txt" #This Google dork will search for password.txt files on a website, which may contain login credentials that can be used by hackers to gain access to a website.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”index of” .htpasswd" #This Google dork will search for .htpasswd files on a website, which may contain encrypted passwords that can be cracked by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “.ssh”" #This Google dork will search for .ssh directories on a website, which may contain SSH keys that can be used by hackers to gain access to a website.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:php | ext:asp | ext:aspx | ext:jsp" #This Google dork will search for PHP, ASP, ASPX, or JSP files on a website, which may contain vulnerabilities that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”index of” db_backup.sql | db.sql | database.sql | sql | .sql.gz | .sql.bz2" #This Google dork will search for database backups and SQL files on a website, which may contain sensitive information such as login credentials or personal information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:pdf “Confidential” | “Secret” | “Classified”" #This Google dork will search for PDF files on a website that contain sensitive information marked as confidential, secret, or classified.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/cgi-bin/ + intext:”User ID” + intext:”Password”" #This Google dork will search for CGI scripts on a website that require login credentials, which may be vulnerable to brute-force attacks.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “backup”" #This Google dork will search for backup files on a website, which may contain sensitive information such as login credentials or personal information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:”/wp-content/uploads/” + intext:”Index of /”" #This Google dork will search for WordPress upload directories on a website, which may contain sensitive files that have been uploaded by users.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:wp-config.php" #This Google dork will search for WordPress configuration files on a website, which may contain database credentials and other sensitive information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:server-status" #This Google dork will search for server status pages on a website, which can reveal information about a server’s configuration and performance.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:doc | ext:docx | ext:pdf | ext:xls | ext:xlsx | ext:ppt | ext:pptx" #This Google dork will search for Microsoft Office and PDF files on a website, which may contain sensitive information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/api/" # — This Google dork will search for API endpoints on a website, which may be vulnerable to attacks such as SQL injection or cross-site scripting (XSS).
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:php intitle:phpinfo “published by the PHP Group”" # — This Google dork will search for PHP info pages on a website, which can reveal information about a website’s PHP configuration that can be useful for hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”index of” “.git”" # — This Google dork will search for Git directories on a website, which may contain sensitive information such as passwords or access tokens.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:env" # — This Google dork will search for .env files on a website, which may contain sensitive information such as API keys or login credentials.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/wp-json/wp/v2/users/" # — This Google dork will search for WordPress user APIs on a website, which may reveal information about users that can be useful for hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/plugins/servlet/watermark/" # — This Google dork will search for Atlassian JIRA Watermark plugins on a website, which may be vulnerable to remote code execution (RCE) attacks.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”Sign in” | intext:”Sign in to” | intext:”Log in” | intext:”Log in to”" # — This Google dork will search for login pages on a website, which may have vulnerabilities that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “web.config”" # — This Google dork will search for web.config files on a website, which may contain sensitive information such as database connection strings or application secrets.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/cgi-bin/login.cgi" # — This Google dork will search for login pages for CGI scripts on a website, which may be vulnerable to brute-force attacks.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:sql | ext:dbf | ext:mdb" # — This Google dork will search for database files on a website, which may contain sensitive information such as login credentials or personal information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:”/manage/advanced/”" # — This Google dork will search for advanced management pages on a website, which may reveal sensitive information or provide access to sensitive functionality.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/conf/" # — This Google dork will search for configuration directories on a website, which may contain sensitive information such as database credentials or API keys.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/cgi-bin/ + intext:”login” + intext:”password”" # — This Google dork will search for CGI scripts on a website that require login credentials, which may be vulnerable to brute-force attacks.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”Powered by” AND intext:”PHP Version”" # — This Google dork will search for websites that are powered by PHP and reveal the PHP version, which can be useful for identifying vulnerabilities in PHP applications.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”index of” “.htpasswd”" # — This Google dork will search for .htpasswd files on a website, which may contain passwords and user information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:wp-includes | inurl:wp-content | inurl:wp-admin | inurl:wp-login.php" # — This Google dork will search for common WordPress directories and files on a website, which may reveal vulnerabilities or provide access to sensitive functionality.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/api/v1" # — This Google dork will search for API v1 endpoints on a website, which may reveal information about users or provide access to sensitive functionality.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “config.json”" # — This Google dork will search for config.json files on a website, which may contain sensitive information such as API keys or database credentials.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:php intext:”Powered by” AND intext:”admin”" # — This Google dork will search for administrative pages of PHP-powered websites, which may have vulnerabilities that can be exploited by hackers.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:/mailman/listinfo/" # — This Google dork will search for Mailman mailing lists on a website, which may reveal email addresses and other sensitive information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “error_log”" # — This Google dork will search for error_log files on a website, which may contain sensitive information such as file paths or debug information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:env intext:DB_USERNAME" # — This Google dork will search for .env files that contain database username information on a website.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:”/admin/user/”" # — This Google dork will search for user administration pages on a website, which may provide access to sensitive functionality or reveal user information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:”Index of /” “php.ini”" # — This Google dork will search for php.ini files on a website, which may contain sensitive information such as database credentials or API keys.
google-chrome --new-tab "https://www.google.com/search?q=site:$url inurl:admin.php intext:”username” intext:”password”" # — This Google dork will search for administrative login pages on a website that require username and password credentials.
google-chrome --new-tab "https://www.google.com/search?q=site:$url filetype:txt | filetype:log | filetype:xml | filetype:ini | filetype:conf | filetype:cnf | filetype:reg | filetype:inf" # — This Google dork will search for various types of configuration files on a website that may contain sensitive information.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intext:”Web Explorer Server — Login”" # — This Google dork will search for login pages for the Web Explorer Server, which may be vulnerable to brute-force attacks or other exploits.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index.of" intext:"api.txt” # — The query is like finding a needle in a digital haystack, It helps you locate publicly available API key files, These files might contain sensitive authentication credentials that, if exposed, could lead to unauthorized access to valuable systems.
google-chrome --new-tab "https://www.google.com/search?q=site:$url ext:php inurl:"api.php?action="" # — Remember the adage “History repeats itself”? The query ext:php inurl:"api.php?action=" is a stark reminder of this. It locates sites that might be susceptible to a XenAPI SQL injection vulnerability. While this query was first posted in 2016, its relevance persists today, with a staggering 141,000 results showcasing its continued significance.
google-chrome --new-tab "https://www.google.com/search?q=site:$url intitle:"index of" api_key OR "api key" OR apiKey -pool" # — Among these queries, a favorite stands out: intitle:"index of" api_key OR "api key" OR apiKey -pool. This gem uncovers potentially exposed API keys. An exposed API key is akin to handing over the keys to your digital kingdom. This query helps identify those instances so that appropriate measures can be taken to secure the keys.


